### ISSUE TITLE
Allow autostart of plugin

### ISSUE THREAD

**Issue by nutellaordidnthappen** [ploppyperson/AutoTorch#2]
Everytime someone joins they have to enable the plugin via GUI. Could there be a config option to login with AutoTorch enabled?

**Comment by ploppyperson** [comment]
Did you find a solution?

**Comment by nutellaordidnthappen** [comment]
No, unfortunately I have not. I guess once the setting stayed “enabled” between two logins on Java client but since then it again starts as “disabled” - but I closed the issue as I thought I mislooked how it works and that I was wrong.  But at least on Bedrock clients it always starts disabled.

**Comment by ploppyperson** [comment]
Will be added in 2.1 https://github.com/Nathat23/AutoTorch/pull/4
