### ISSUE TITLE
typing /at make an exception trying to execute this command

### ISSUE THREAD

**Issue by SilenceryKoriyuka** [ploppyperson/AutoTorch#7]
![image](https://github.com/user-attachments/assets/a12b6e56-25dd-4372-8e37-746c5600ccb2)

If the image above is attach, there is an error after I type the /at command, I run PaperMC 1.21 server and latest Plugin version

**Comment by SilenceryKoriyuka** [comment]
![image](https://github.com/user-attachments/assets/f8e22360-59f5-4b27-a406-39f6c082b6bd)

This is what happen in the console when I type it

**Comment by ploppyperson** [comment]
Is this a new install?

Could you upload your AutoTorch config folder somewhere?

**Comment by SilenceryKoriyuka** [comment]
![image](https://github.com/user-attachments/assets/fa4aa4c7-ff4c-4496-a54e-1181072e540f)
![image](https://github.com/user-attachments/assets/b2e4237c-5cbf-48eb-ab65-14595632684b)
![image](https://github.com/user-attachments/assets/05c60fe6-26bd-4d28-9f99-81458620d23f)


This is all 3 file in the config

**Comment by SilenceryKoriyuka** [comment]
> Is this a new install?

Yes, this is indeed a new install

**Comment by ploppyperson** [comment]
Do you have a 'player-data' folder inside the AutoTorch folder?

**Comment by Weltensiedler** [comment]
We have the same problem. Fresh Install, Playerdata Folder exists with empty player-datafiles. We are using Purpur 1.20.4

**Comment by ploppyperson** [comment]
Thanks for the error report. This will be fixed in the next release.
